name: Build Windows Only

on:
  push:
    branches:
      - "master"

jobs:
  buildwindows:
    name: Windows x64
    runs-on: windows-latest

    steps:      
      - name: Prepare Qt Libraries
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
          modules: 'qtbase'

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Clone
        uses: actions/checkout@v3
      
      - name: Compile
        run: |
          qmake SavvyCAN.pro
          mingw32-make

      - name: Package
        run: |
          mkdir package
          copy "release\SavvyCAN.exe" package\
          mkdir package\help
          copy help\*.md package\help\
          mkdir package\help\images
          copy help\images\*.* package\help\images\
          mkdir package\examples
          copy examples\*.* package\examples\
          copy "%Qt5_Dir%\bin\Qt5Core.dll" package\
          copy "%Qt5_Dir%\bin\Qt5Gui.dll" package\
          copy "%Qt5_Dir%\bin\Qt5Network.dll" package\
          copy "%Qt5_Dir%\bin\Qt5PrintSupport.dll" package\
          copy "%Qt5_Dir%\bin\Qt5Qml.dll" package\
          copy "%Qt5_Dir%\bin\Qt5SerialBus.dll" package\
          copy "%Qt5_Dir%\bin\Qt5SerialPort.dll" package\
          copy "%Qt5_Dir%\bin\Qt5Widgets.dll" package\
          mkdir package\imageformats
          copy "%Qt5_Dir%\plugins\imageformats\*.*" package\imageformats\
          mkdir package\platforms
          copy "%Qt5_Dir%\plugins\platforms\*.*" package\platforms\
          mkdir package\styles
          copy "%Qt5_Dir%\plugins\styles\*.*" package\styles\
          mkdir package\canbus
          copy "%Qt5_Dir%\plugins\canbus\*.*" package\canbus\

      - uses: actions/upload-artifact@v4
        with:
          name: SavvyCAN-Windows_x64
          path: package
