name: Build SavvyCAN for Windows

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw81'
        dir: '${{ runner.temp }}/qt'
        modules: 'qtbase'

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Build with qmake
      run: |
        qmake SavvyCAN.pro
        mingw32-make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SavvyCAN-exe
        path: |
          SavvyCAN.exe
          release/SavvyCAN.exe
